import React from 'react';
import { Shield, FileText, RefreshCw, Fingerprint, Lock, UserCheck, CreditCard, LogOut, Scale, Activity, Globe, Info, AlertTriangle, Database, Mail, Share2, Building2, Search } from 'lucide-react';

export interface LegalSection {
    title: string;
    content: string;
    subsections?: { subtitle: string; body: string }[];
}

export interface LegalPage {
    title: string;
    lastUpdated: string;
    icon: React.ReactNode;
    executiveSummary: string;
    articles: LegalSection[];
}

// Environment-based contact configuration
const CONFIG = {
    supportEmail: import.meta.env?.VITE_SUPPORT_EMAIL || 'lovneetrathi@gmail.com',
    supportPhone: import.meta.env?.VITE_SUPPORT_PHONE || '+91 9413821007',
    dpoName: import.meta.env?.VITE_DPO_NAME || 'Lavneet Rathi'
};

export const LEGAL_CONTENT: Record<string, LegalPage> = {
    'privacy-policy': {
        title: 'Privacy Policy',
        lastUpdated: 'February 15, 2026',
        icon: <Shield size={24} className="text-emerald-400" />,
        executiveSummary: 'This Privacy Policy is a comprehensive legal document governing the collection, processing, and management of data by TallyLink. We adhere to the highest international standards of data protection, including India?s Digital Personal Data Protection (DPDP) Act 2023 and the spirit of GDPR. This document outlines our "Zero-Trust" data architecture and your rights as a data principal.',
        articles: [
            {
                title: 'Article 1: Scope and Applicability',
                content: 'This policy applies to all services provided by TallyLink, including the Desktop Sync Engine, Cloud Dashboard, Mobile Applications, and API Interfaces. It covers all "Personal Data" and "Business Sensitive Data" (BSD) as defined under Indian Information Technology laws.',
                subsections: [
                    { subtitle: '1.1 Geographic Scope', body: 'While our primary operations are in India, this policy covers users globally, applying the most stringent of either local or international data laws where applicable.' },
                    { subtitle: '1.2 Service Scope', body: 'This covers automated sync, manual uploads, support interactions, and third-party integrations (WhatsApp/Email).' }
                ]
            },
            {
                title: 'Article 2: Definitions and Interpretations',
                content: 'To ensure absolute clarity, the following terms are defined for the purpose of this agreement:',
                subsections: [
                    { subtitle: '2.1 Data Fiduciary', body: 'The User or Entity that determines the purpose and means of processing the accounting data (You).' },
                    { subtitle: '2.2 Data Processor', body: 'TallyLink Technologies, which processes data only as per the instructions of the Data Fiduciary.' },
                    { subtitle: '2.3 BSD (Business Sensitive Data)', body: 'Any financial data including turnover, profit margins, credit limits, and tax liabilities extracted from Tally ERP.' },
                    { subtitle: '2.4 Encryption at Rest', body: 'Data stored in our databases using AES-256-GCM algorithms.' }
                ]
            },
            {
                title: 'Article 3: Technical Data Collection Protocols',
                content: 'Our data collection is limited to what is strictly necessary for providing Tally cloud analytics. We utilize non-invasive extraction methods designed to minimize impact on local compute resources.',
                subsections: [
                    { subtitle: '3.1 XML/ODBC Extraction', body: 'The sync engine uses Tally?s native XML/ODBC interface. We do not modify the Tally.exe or binary files. This ensures your Tally ERP remains eligible for official support from Tally Solutions Pvt. Ltd.' },
                    { subtitle: '3.2 Field-Level Mapping', body: 'We only collect: Voucher IDs, Party Names, GSTINs, HSNs, Amounts, and Inventory Quantities. We specifically do not collect non-accounting files from your hard drive, nor do we access browser history or other personal documents.' },
                    { subtitle: '3.3 Metadata Collection', body: 'IP Address, MAC ID, Tally Serial Number, and OS version are logged for license verification and security auditing. This metadata is stored separately from financial data to prevent cross-correlation during unauthorized access.' },
                    { subtitle: '3.4 Log Persistence', body: 'Local logs generated by the sync engine are rotated every 7 days to prevent excessive disk consumption. Cloud-side audit logs are maintained for 180 days in compliance with Indian CERT-In guidelines.' }
                ]
            },
            {
                title: 'Article 4: Detailed Processing Operations',
                content: 'Data processing involves several stages intended to transform raw ERP data into actionable insights for business owners and auditors.',
                subsections: [
                    { subtitle: '4.1 Real-time Transformation', body: 'Data is converted from Tally XML to a normalized JSON Schema. During this phase, invalid data formats are rejected to maintain cloud database integrity.' },
                    { subtitle: '4.2 Aggregation and Indexing', body: 'Data is aggregated to create Balance Sheets and P&L statements in real-time. Indexing is performed on Party Names and Voucher Types to ensure sub-second query performance.' },
                    { subtitle: '4.3 Anomaly Detection AI', body: 'Our proprietary machine learning algorithms scan for duplicate vouchers, missing GST numbers, or potential ITC mismatches. This processing is performed in a Zero-Knowledge environment where the AI "sees" hashes rather than plain-text party names.' },
                    { subtitle: '4.4 Reporting Latency', body: 'Processing latency is typically < 2 seconds from the moment a packet reaches our cloud perimeter. However, large data imports (>50,000 vouchers) may be subject to background queueing.' }
                ]
            },
            {
                title: 'Article 5: Security Architecture (SOC 2 Alignment)',
                content: 'We implement rigorous Technical and Organizational Measures (TOMs) to defend against unauthorized access, hardware failure, and insider threats.',
                subsections: [
                    { subtitle: '5.1 Network Security', body: 'Firewalls with Deep Packet Inspection (DPI) and WAF (Web Application Firewall) protect our cloud endpoints. All traffic must pass through a DDoS mitigation layer (Cloudflare/Google Armor).' },
                    { subtitle: '5.2 Identity Management', body: 'Multi-Factor Authentication (MFA) via TOTP or SMS is mandatory for administrative access. Session tokens utilize HMAC-SHA256 signatures and vary per device to prevent session hijacking.' },
                    { subtitle: '5.3 Disaster Recovery', body: 'Automated 15-minute point-in-time recovery (PITR) backups are maintained in separate Availability Zones. We perform monthly recovery drills to ensure data integrity during catastrophic outages.' },
                    { subtitle: '5.4 Cryptographic Keys', body: 'User-specific encryption keys are managed via a Hardware Security Module (HSM). TallyLink staff do not have access to these keys in plain text.' }
                ]
            },
            {
                title: 'Article 6: Data Subject Access Rights (DSAR)',
                content: 'Consistent with DPDP Act 2023, you have full sovereign control over your data. We provide self-service tools to exercise these rights immediately.',
                subsections: [
                    { subtitle: '6.1 Right to Withdraw Consent', body: 'Consent can be withdrawn at any time via the "Danger Zone" in settings. This triggers the immediate permanent cryptographic wiping of your cloud keys and schedules your data for deletion.' },
                    { subtitle: '6.2 Right to Correction', body: 'Users can trigger a "Force Re-sync" to overwrite incorrect cloud data with fresh Tally data. This ensures the dashboard always reflects the "Single Source of Truth" (Your Tally ERP).' },
                    { subtitle: '6.3 Data Portability', body: 'Users can export their entire cloud database in a normalized Excel/CSV format at any time. This prevents vendor lock-in and allows for independent audits.' },
                    { subtitle: '6.4 Grievance Officer', body: `If a DSAR request is not fulfilled within 15 days, users may escalate directly to our Grievance Officer at ${CONFIG.supportEmail}.` }
                ]
            },
            {
                title: 'Article 7: Third-Party Sub-processors',
                content: 'We utilize a curated list of vendors to offer our services. All vendors are subject to strict DPAs (Data Processing Addendums) and annual security reviews.',
                subsections: [
                    { subtitle: '7.1 Infrastructure', body: 'Supabase (Google Cloud) for Database, Vercel for Frontend, and Firebase for Notifications. These providers are chosen for their high-availability and security certifications.' },
                    { subtitle: '7.2 Communication', body: 'Razorpay for Payments, Twilio for WhatsApp Alerts. These providers only receive the minimum data required to execute their specific function.' },
                    { subtitle: '7.3 Data Localization', body: 'For Indian customers, we enforce data localization, ensuring that your primary financial database resides in cloud regions within India (Mumbai/Hyderabad).' }
                ]
            },
            {
                title: 'Article 8: Data Retention and Deletion Policy',
                content: 'We adhere to a "Least-time" retention principle. Data is kept only as long as it provides value for your accounting analysis.',
                subsections: [
                    { subtitle: '8.1 Active Subscription', body: 'During an active subscription, we retain up to 7 years of Tally history (as per Income Tax Act requirements) unless the user requests partial deletion.' },
                    { subtitle: '8.2 Post-Expiration', body: 'If a subscription is not renewed, data is moved to Cold Storage for 30 days. After 30 days, all voucher data is permanently purged from our production clusters.' },
                    { subtitle: '8.3 Backup Erasure', body: 'Permanent deletion from backups occurs within a 90-day cycle, ensuring that even disaster recovery snapshots do not contain data beyond its legal lifespan.' }
                ]
            },
            {
                title: 'Article 9: Compliance and Regulatory Supervision',
                content: 'TallyLink operates under the jurisdiction of the Republic of India and adheres to the latest digital mandates.',
                subsections: [
                    { subtitle: '9.1 IT Act 2000', body: 'We maintain compliance with Section 43A of the Information Technology Act and the "Reasonable Security Practices" rules of 2011.' },
                    { subtitle: '9.2 DPDP Act 2023', body: 'As a Data Processor, we fulfill our duties toward the Data Fiduciary (The User) as defined under the new Digital Personal Data Protection Act.' },
                    { subtitle: '9.3 Law Enforcement Requests', body: 'We only disclose data to law enforcement upon receipt of a valid, legally-binding warrant issued by a competent court in India.' }
                ]
            },
            {
                title: 'Article 10: Specific Data Element processing (Voucher Schema)',
                content: 'We provide a granular breakdown of how individual accounting data fields are processed and stored within our distributed systems.',
                subsections: [
                    { subtitle: '10.1 Sales & Purchase Vouchers', body: 'Extracted fields: Date, Reference No, Party Ledger, Item Name, Quantity, Rate, Amount, GST Rate, HSN/SAC code. Purpose: Generating GSTR-1, GSTR-3B summaries and Sales/Purchase Analysis.' },
                    { subtitle: '10.2 Inventory Records', body: 'Extracted fields: Stock Item Name, Part Number, Opening Balance, Closing Balance, Standard Cost. Purpose: Inventory ageing reports and stock-level alerts.' },
                    { subtitle: '10.3 Ledger Master Data', body: 'Extracted fields: Party Alias, Opening Balance, Current Balance, Credit Days, Credit Limit. Purpose: Creditor/Debitor monitoring and Outstanding aging analysis.' }
                ]
            },
            {
                title: 'Article 11: Automated Decision Making and Profiling',
                content: 'TallyLink utilizes advanced heuristic models to assist in financial health monitoring. This process is strictly advisory.',
                subsections: [
                    { subtitle: '11.1 Credit Worthiness Heuristics', body: 'Our algorithms analyze your payment cycles to provide internal scores on credit-worthiness. This data is never shared with external agencies like CIBIL without explicit opting-in.' },
                    { subtitle: '11.2 Expense Trend Profiling', body: 'AI models identifies anomalies in overhead expenses, alerting the user to potential billing leakages or department-wise budget overruns.' }
                ]
            },
            {
                title: 'Article 12: Administrative Access and Insider Threat Control',
                content: 'We maintain strict internal protocols to ensure your financial secrecy is never compromised by our staff.',
                subsections: [
                    { subtitle: '12.1 Principle of Least Privilege (PoLP)', body: 'Support engineers have NO access to your voucher data. Access is only granted via a "Time-Bound Support Token" which you must generate and share during a debugging session.' },
                    { subtitle: '12.2 Background Verification', body: 'All TallyLink employees with "Cloud Operative" clearance undergo mandatory 10-year criminal background checks and sign irrevocable non-disclosure agreements (NDAs).' }
                ]
            },
            {
                title: 'Article 13: International Data Transfer Protocols (Extra-Territorial)',
                content: 'For our international users, we ensure that data crossing borders remains under a protective shell of modern crypto-norms.',
                subsections: [
                    { subtitle: '13.1 Standard Contractual Clauses (SCCs)', body: 'In the absence of an adequacy decision, all data transfers to overseas backup nodes are governed by current SCCs as approved by the European Commission and relevant Indian nodes.' },
                    { subtitle: '13.2 Trans-Border Accountability', body: 'We remain fully liable for the actions of our infrastructure sub-processors regarding the security of your data, regardless of their geographic location.' }
                ]
            },
            {
                title: 'Article 14: Data Sovereignty and Legislative Supremacy',
                content: 'This document is structured to prioritize the legal sovereignty of the Data Principal (The User).',
                subsections: [
                    { subtitle: '14.1 Supremacy of DPDP Act', body: 'In the event of a conflict between our global policies and the India DPDP Act 2023, the provisions of the DPDP Act shall prevail for all data gathered within the Indian territory.' },
                    { subtitle: '14.2 Right to Nomination', body: 'Consistent with Section 10 of DPDP Act, users may nominate a legal representative to exercise data rights in the event of death or incapacity. This can be configured in "Account Contingency" settings.' }
                ]
            },
            {
                title: 'Article 15: Cookie-less Telemetry and Fingerprinting Prevention',
                content: 'We avoid invasive tracking technologies that compromise browser privacy.',
                subsections: [
                    { subtitle: '15.1 Zero Fingerprinting', body: 'We do not collect canvas data, font-lists, or screen resolution patterns to "fingerprint" your browser for tracking purposes.' },
                    { subtitle: '15.2 Functional Telemetry', body: 'We only log dashboard performance metrics (page load times, error rates) to maintain our 99.9% SLA.' }
                ]
            },
            {
                title: 'Article 16: Public Cloud Isolation Architecture',
                content: 'Our multi-tenant database is designed with "Logical Silos" to prevent data bleeding between accounts.',
                subsections: [
                    { subtitle: '16.1 RLS (Row Level Security)', body: 'Every query executed by our API is strictly intercepted by Row Level Security policies. It is mathematically impossible for User A to query User B?s records, even in the event of an API bug.' },
                    { subtitle: '16.2 Encrypted Search', body: 'Search queries on Party Names utilize Blind Indexing, meaning the database engine can find your records without ever knowing the actual "un-encrypted" name of your party.' }
                ]
            },
            {
                title: 'Article 17: Vulnerability Disclosure and Bug Bounty',
                content: 'We reward the ethical security community for helping us harden our defenses.',
                subsections: [
                    { subtitle: '17.1 Reporting Portal', body: 'Security researchers are invited to report potential flaws via security@tallylink.cloud. We offer rewards ranging from ₹10,000 to ₹5,00,000 based on criticality.' },
                    { subtitle: '17.2 Safe Harbor', body: 'We pledge not to initiate legal action against researchers who discover a vulnerability and report it responsibly without exploiting or leaking user data.' }
                ]
            },
            {
                title: 'Article 18: Notification of Significant Changes',
                content: 'This policy is a living document, evolving with shifting legal landscapes.',
                subsections: [
                    { subtitle: '18.1 Notice Period', body: 'Material changes (e.g., adding a new type of data collection) will be notified 30 days in advance via Dashboard pop-ups and Registered Email.' },
                    { subtitle: '18.2 Non-acceptance', body: 'If you do not agree to the updated terms, you have the right to export your data and terminate your account within the 30-day notice period.' }
                ]
            },
            {
                title: 'Article 19: Governing Law and Contact',
                content: 'This policy is governed by the laws of the Republic of India.',
                subsections: [
                    { subtitle: '19.1 Legal Address', body: 'TallySync Technologies Pvt Ltd, [Jaipur Office], Rajasthan, India.' },
                    { subtitle: '19.2 Direct Escalation', body: 'Queries regarding this policy can be addressed to privacy@tallylink.cloud.' }
                ]
            },
            {
                title: 'Article 20: Data Processing during Beta Feature Participation',
                content: 'Provisions for users opting into early-access or experimental analytics modules.',
                subsections: [
                    { subtitle: '20.1 Experimental Tracking', body: 'Beta features may involve additional telemetry logging to identify edge-case bugs. Users are notified before enabling such modules.' },
                    { subtitle: '20.2 Non-Production Workloads', body: 'We recommend using "Restricted Data Sets" when testing beta sync protocols to maintain maximum safety.' }
                ]
            },
            {
                title: 'Article 21: Usage of Anonymized Data for Industry Benchmarking',
                content: 'How we contribute to accounting intelligence without compromising individual secrecy.',
                subsections: [
                    { subtitle: '21.1 Aggregated Insights', body: 'We may use fully anonymized, aggregated data (e.g., "Average GST liability in the Textile sector") to provide benchmark reports to our community.' },
                    { subtitle: '21.2 Irreversibility', body: 'Anonymization is performed using k-anonymity and differential privacy techniques to ensure that individual business identities can never be reverse-engineered.' }
                ]
            },
            {
                title: 'Article 22: Privacy-by-Design and Default (PbD)',
                content: 'Our structural commitment to data protection from the first line of code.',
                subsections: [
                    { subtitle: '22.1 Engineering Lifecycle', body: 'Every new feature undergoes a Data Protection Impact Assessment (DPIA) before development begins.' },
                    { subtitle: '22.2 Minimum Data Footprint', body: 'Our systems are designed to automatically reject data packets that contain fields not explicitly mapped in our schemas.' }
                ]
            }
        ]
    },
    'terms-and-conditions': {
        title: 'Terms of Service',
        lastUpdated: 'February 15, 2026',
        icon: <FileText size={24} className="text-blue-400" />,
        executiveSummary: 'These Terms of Service (ToS) are a legally binding agreement between the Licensee and TallyLink Technologies. They govern your use of the TallyLink ecosystem, including all software components, support services, and legal liabilities.',
        articles: [
            {
                title: 'Article 1: License Grant and Usage',
                content: 'We grant you a non-exclusive, non-transferable license to use TallyLink. This license is tied to your Tally Serial Number and Auth Credentials.',
                subsections: [
                    { subtitle: '1.1 Single Entity Use', body: 'Unless an Enterprise/CA plan is purchased, a single license applies to one Tally Serial Number only.' },
                    { subtitle: '1.2 Intellectual Property', body: 'TallyLink remains the sole property of the developers. You may not decompile or reverse engineer the sync protocols.' }
                ]
            },
            {
                title: 'Article 2: User Responsibilities',
                content: 'You are responsible for the validity of the data synchronized and the security of your account.',
                subsections: [
                    { subtitle: '2.1 Local Environment', body: 'You must ensure Tally ERP is running on a compatible Windows environment with valid ODBC configurations.' },
                    { subtitle: '2.2 Credential Security', body: 'Leaked credentials resulting in data breach are the sole responsibility of the User.' }
                ]
            },
            {
                title: 'Article 3: Commercial Terms',
                content: 'Pricing is based on active sync companies. All fees are in INR and subject to 18% GST.',
                subsections: [
                    { subtitle: '3.1 Subscription Tiers', body: 'Basic, Pro, and Enterprise tiers offer different sync frequencies and data retention periods.' },
                    { subtitle: '3.2 Refund Policy', body: 'Refunds are governed by the specific Refund & Cancellation policy documented on our portal.' }
                ]
            },
            {
                title: 'Article 4: Limitation of Liability',
                content: 'To the maximum extent permitted by law, our liability is strictly capped.',
                subsections: [
                    { subtitle: '4.1 Financial Capping', body: 'Our total liability shall not exceed the subscription amount paid by you in the 6 months preceding any claim.' },
                    { subtitle: '4.2 No Indirect Damages', body: 'We are not liable for lost profits, loss of data, or statutory penalties imposed due to discrepancies in reports.' }
                ]
            },
            {
                title: 'Article 5: Indemnification',
                content: 'You agree to defend and indemnify TallyLink against any claims arising from your misuse of the platform.',
                subsections: [
                    { subtitle: '5.1 Third-Party Claims', body: 'If your synchronization of invalid/fraudulent data leads to a tax audit or penalty, you indemnify us fully.' }
                ]
            },
            {
                title: 'Article 6: Termination and Suspension',
                content: 'Accounts may be suspended for non-payment or breach of acceptable use rules.',
                subsections: [
                    { subtitle: '6.1 Auto-Termination', body: 'Accounts inactive for more than 180 days with zero payment will be automatically purged.' }
                ]
            },
            {
                title: 'Article 7: Governing Law and Dispute Resolution',
                content: 'This agreement is governed by the laws of India.',
                subsections: [
                    { subtitle: '7.1 Arbitration', body: 'Disputes will be settled via binding arbitration in Jaipur/New Delhi under the Arbitration and Conciliation Act, 1996.' },
                    { subtitle: '7.2 Jurisdiction', body: 'Subject to arbitration, the courts of Rajasthan shall have exclusive jurisdiction.' }
                ]
            },
            {
                title: 'Article 8: Acceptable Use and Network Integrity',
                content: 'We maintain strict guardrails to protect our cloud infrastructure from malicious exploitation.',
                subsections: [
                    { subtitle: '8.1 Prohibition of Benchmarking', body: 'Users may not perform competitive benchmarking or stress tests on the TallyLink API without written consent.' },
                    { subtitle: '8.2 Automated Extraction', body: 'Using headless browsers or scrapers to extract data from the TallyLink Dashboard is a violation of these terms and will result in IP-level blacklisting.' }
                ]
            },
            {
                title: 'Article 9: Enterprise and Multi-GSTIN Management',
                content: 'Provisions for organizations managing multiple legal entities through a single TallyLink dashboard.',
                subsections: [
                    { subtitle: '9.1 Entity Isolation', body: 'Each GSTIN added to the dashboard requires a valid license. Cross-company data sharing is only permitted through authorized Accountant VIEWS.' },
                    { subtitle: '9.2 Administrative Responsibility', body: 'The primary account holder is liable for the access permissions granted to sub-users (Employees/CAs).' }
                ]
            },
            {
                title: 'Article 10: Software Modifications and Versioning',
                content: 'Our commitment to continuous improvement requires periodic updates to core sync components.',
                subsections: [
                    { subtitle: '10.1 Forced Updates', body: 'To maintain security, TallyLink may push mandatory updates to the Desktop Sync component. Failure to update may result in sync suspension.' },
                    { subtitle: '10.2 Feature Deprecation', body: 'We reserve the right to deprecate features with a 60-day notice if they become obsolete or legally non-compliant.' }
                ]
            },
            {
                title: 'Article 11: Third-Party Integrations (WhatsApp/Cloud)',
                content: 'TallyLink acts as a bridge between Tally and third-party APIs.',
                subsections: [
                    { subtitle: '11.1 API Limits', body: 'Integration with WhatsApp is subject to Meta Platforms’ Business API terms and rate limits.' },
                    { subtitle: '11.2 Data Transit', body: 'We are not responsible for delays in data delivery caused by third-party gateway providers.' }
                ]
            },
            {
                title: 'Article 12: Force Majeure and Infrastructure Acts of God',
                content: 'Defining limits of responsibility during extraordinary global or local events.',
                subsections: [
                    { subtitle: '12.1 Defined Events', body: 'Events include cyber-wars, nationwide internet shutdowns, data center fires, or sudden changes in Indian tax laws that make software operation illegal.' },
                    { subtitle: '12.2 Remediation', body: 'During Force Majeure, our SLA commitments are suspended until normal infrastructure services resume.' }
                ]
            },
            {
                title: 'Article 13: Disclaimer of Warranties (AS-IS)',
                content: 'Standard industry legal protections regarding software performance.',
                subsections: [
                    { subtitle: '13.1 No Error-Free Guarantee', body: 'While we strive for perfection, we do not warrant that the software will be 100% error-free or that all Tally customizations (TDLs) will sync perfectly.' },
                    { subtitle: '13.2 Environmental Dependency', body: 'Performance is dependent on the User’s local hardware, Windows OS version, and ODBC driver health.' }
                ]
            },
            {
                title: 'Article 14: Publicity and Corporate Branding',
                content: 'Usage of names and logos for marketing and relationship purposes.',
                subsections: [
                    { subtitle: '14.1 User Metadata', body: 'We may list your company name in our "Trusted By" section unless you explicitly opt-out via a support ticket.' }
                ]
            },
            {
                title: 'Article 15: Confidentiality and Data Secrecy',
                content: 'Ensuring your business secrets remain private during the term of service.',
                subsections: [
                    { subtitle: '15.1 Definition of Secrets', body: 'This includes your profit margins, vendor names, and customer lists extracted from Tally.' },
                    { subtitle: '15.2 Non-Disclosure', body: 'We will not sell, rent, or lease your financial data to any third-party marketing or credit agencies.' }
                ]
            },
            {
                title: 'Article 16: Severability and survival',
                content: 'Legal continuity of the agreement in the face of specific clause invalidation.',
                subsections: [
                    { subtitle: '16.1 Clause Independence', body: 'If a court finds one clause invalid, all other clauses remain in full force and effect.' },
                    { subtitle: '16.2 Surviving Terms', body: 'Privacy, Liability, and Dispute Resolution clauses survive the termination of your subscription.' }
                ]
            },
            {
                title: 'Article 17: Entire Agreement',
                content: 'This document represents the final and complete understanding between the parties.',
                subsections: [
                    { subtitle: '17.1 Superseding Clause', body: 'This ToS supersedes any prior oral or written advertisements, proposals, or representations.' }
                ]
            },
            {
                title: 'Article 18: Anti-Bribery and Corruption Compliance',
                content: 'Our commitment to ethical business conduct across all jurisdictions.',
                subsections: [
                    { subtitle: '18.1 Zero Tolerance', body: 'TallyLink prohibits any form of bribery or kick-backs for license procurement. Violation by a user leads to immediate contract termination and reporting to the relevant authorities.' }
                ]
            },
            {
                title: 'Article 19: Export Control and Sanctions',
                content: 'Adhering to international trade compliance and legislative mandates.',
                subsections: [
                    { subtitle: '19.1 Denied Entities', body: 'Users guarantee they are not listed on any Indian or international trade sanction lists. Use in sanctioned territories is strictly prohibited and subject to automatic blocking.' }
                ]
            },
            {
                title: 'Article 20: No Agency or Partnership Relationship',
                content: 'Clarifying the nature of the relationship between TallyLink and the User.',
                subsections: [
                    { subtitle: '20.1 Independent Contractors', body: 'Nothing in this agreement shall be construed as creating a partnership, joint venture, or agency relationship. Each party operates as an independent legal entity.' }
                ]
            }
        ]
    },
    'refund-policy': {
        title: 'Refund & Cancellation',
        lastUpdated: 'February 15, 2026',
        icon: <RefreshCw size={24} className="text-orange-400" />,
        executiveSummary: 'This document specifies the terms under which TallyLink Cloud services may be cancelled and the conditions for eligibility for financial restitution. We operate a strict digital entitlement framework.',
        articles: [
            {
                title: 'Article 1: Digital Provisioning and Instant Consumption',
                content: 'TallyLink provides SaaS (Software-as-a-Service) which is provisioned instantly upon successful payment. Due to the nature of digital licensing, services are deemed "consumed" the moment the first synchronization packet is received by our cloud nodes.',
                subsections: [
                    { subtitle: '1.1 Activation defined', body: 'Activation occurs when the user binds a Tally Serial Number to their Cloud Dashboard and initiates the first handshake. Post-activation, standard refunds are prohibited.' }
                ]
            },
            {
                title: 'Article 2: Grounds for Exceptional Refund Requests',
                content: 'We recognize that technical anomalies can occur. Exceptional refunds are evaluated based on the following criteria:',
                subsections: [
                    { subtitle: '2.1 Non-Compatibility', body: 'If our documented system requirements (Windows 10+, Tally ERP 9/Prime) are met and our support team is unable to establish a connection within 72 hours of intervention.' },
                    { subtitle: '2.2 Double Billing', body: 'Duplicate charges originating from payment gateway latency. Claims must be filed within 48 hours of the transaction.' }
                ]
            },
            {
                title: 'Article 3: Cancellation Deadlines and Proration',
                content: 'Users may cancel their recurring subscriptions at any time via the billing portal.',
                subsections: [
                    { subtitle: '3.1 Mid-cycle Cancellation', body: 'We do not offer prorated refunds for remaining days in a monthly cycle. Access remains until the period expires.' },
                    { subtitle: '3.2 Annual Plans', body: 'Annual plans can be cancelled within 7 days of purchase for a partial refund (pro-rata 11 months) if zero data has been synchronized.' }
                ]
            },
            {
                title: 'Article 4: Promotional and Bundle Refunds',
                content: 'Special conditions apply to discounted bundles or promotional codes.',
                subsections: [
                    { subtitle: '4.1 Bundle Breaking', body: 'If a "Buy 3 months get 1 free" bundle is purchased, cancellation of the paid portion invalidates the free portion automatically.' },
                    { subtitle: '4.2 Non-Refundable Credits', body: 'Credits added via gift cards or referral rewards have zero cash value and are strictly non-refundable.' }
                ]
            },
            {
                title: 'Article 5: Upgrades, Downgrades and Billing Adjustments',
                content: 'How credits are applied during changes in subscription tiers.',
                subsections: [
                    { subtitle: '5.1 Upgrades', body: 'When upgrading (e.g., Basic to Pro), the unused portion of the current month is applied as a credit toward the new tier.' },
                    { subtitle: '5.2 Downgrades', body: 'Downgrades take effect only at the end of the current billing cycle. No refunds are issued for higher-tier features not used during the notice period.' }
                ]
            },
            {
                title: 'Article 6: Partial Service Disruptions and SLA Credits',
                content: 'Restitution protocols for significant platform failures.',
                subsections: [
                    { subtitle: '6.1 Systemic Outages', body: 'If TallyLink Cloud services are unavailable for more than 12 consecutive hours (outside maintenance), users may request an SLA credit equal to 1 day of subscription extension.' }
                ]
            },
            {
                title: 'Article 7: Chargeback Handling and Dispute Integrity',
                content: 'Protocols for handling unauthorized payment escalations.',
                subsections: [
                    { subtitle: '7.1 Immediate Suspension', body: 'Filing a chargeback via a bank without first contacting TallyLink support will result in the immediate and permanent suspension of the associated Tally Serial Number.' },
                    { subtitle: '7.2 Admin Fee', body: 'We reserve the right to charge a ₹1500 administrative fee to cover bank penalties for frivolous chargeback disputes.' }
                ]
            },
            {
                title: 'Article 8: Refund Processing Timeless and Logistics',
                content: 'Expected windows for financial restitution.',
                subsections: [
                    { subtitle: '8.1 Gateway Latency', body: 'Successful refunds are processed within 48 hours from our side, but may take 7-10 business days to reflect in your source account (Cards/UPI/NetBanking).' }
                ]
            },
            {
                title: 'Article 9: Independent Resellers and Partner Purchases',
                content: 'Refunds for licenses bought through third-party CAs or Dealers.',
                subsections: [
                    { subtitle: '9.1 Dealer Finality', body: 'If you purchased TallyLink via an offline Tally Dealer, all refund requests must be directed to the dealer. We cannot issue refunds for payments we did not collect directly.' }
                ]
            },
            {
                title: 'Article 10: Finality of Special Event Sales',
                content: 'Conditions for flash-sales or "Growth Hack" offers.',
                subsections: [
                    { subtitle: '10.1 Flash Sale Clause', body: 'Subscriptions purchased during "Founding Member" or "Black Friday" events are sold under "Binding Finality" and are 100% non-refundable under any circumstance.' }
                ]
            }
        ]
    },
    'cookie-policy': {
        title: 'Cookie Policy',
        lastUpdated: 'February 15, 2026',
        icon: <Fingerprint size={24} className="text-cyan-400" />,
        executiveSummary: 'Transparency in browsing telemetry is core to our trust model. This policy details how we utilize HTTP cookies, local storage, and session tokens.',
        articles: [
            {
                title: 'Article 1: Functional and Security Cookies',
                content: 'Certain data storage on your browser is mandatory for the security and functionality of the TallyLink Dashboard.',
                subsections: [
                    { subtitle: '1.1 JWT Persistence', body: 'We store encrypted JSON Web Tokens (JWT) to maintain your session without requiring per-page logins.' },
                    { subtitle: '1.2 CSRF Shielding', body: 'Anti-forgery tokens are stored to prevent Cross-Site Request Forgery attacks.' }
                ]
            },
            {
                title: 'Article 2: Persistence and Expiry',
                content: 'We distinguish between session-based and persistent storage mechanisms.',
                subsections: [
                    { subtitle: '2.1 Session Storage', body: 'Temporary data such as the currently selected company view is cleared when you close the browser tab.' },
                    { subtitle: '2.2 Local Storage', body: 'Persistent preferences like "Dark Mode" or "Sidebar State" are stored locally on your device.' }
                ]
            }
        ]
    },
    'security-statement': {
        title: 'Security Statement',
        lastUpdated: 'February 15, 2026',
        icon: <Lock size={24} className="text-purple-400" />,
        executiveSummary: 'Security at TallyLink is not a foundation; it is our foundation. This document provides a high-level overview of our multi-layered defense-in-depth architecture.',
        articles: [
            {
                title: 'Article 1: Infrastructure and Physical Security',
                content: 'Our cloud architecture is hosted on enterprise-grade infrastructure managed by world-class providers (Supabase/GCP).',
                subsections: [
                    { subtitle: '1.1 Data Center Compliance', body: 'All physical servers are located in ISO 27001 and SOC 2 Type II compliant data centers.' },
                    { subtitle: '1.2 Biometric Access', body: 'Physical access is restricted via multi-factor biometrics and 24/7 armed security patrols.' }
                ]
            },
            {
                title: 'Article 2: Encryption and Cryptography',
                content: 'Data is protected from the moment it leaves your desktop until it is archived in our vaults.',
                subsections: [
                    { subtitle: '2.1 TLS 1.3 Transport', body: 'All sync traffic is routed through tunnels encrypted with TLS 1.3 and HSTS (HTTP Strict Transport Security).' },
                    { subtitle: '2.2 AES-256 Storage', body: 'Voucher and Ledger fields are encrypted using AES-256-GCM with salt-based key derivation (PBKDF2).' }
                ]
            },
            {
                title: 'Article 3: Vulnerability and Patch Management',
                content: 'We proactively scan for threats and maintain a rigorous patching cycle.',
                subsections: [
                    { subtitle: '3.1 Real-time EDR', body: 'Endpoint Detection and Response systems monitor our cloud nodes for suspicious patterns.' },
                    { subtitle: '3.2 Penetration Testing', body: 'Quarterly gray-box penetration tests are conducted by independent third-party security auditors.' }
                ]
            }
        ]
    },
    'acceptable-use-policy': {
        title: 'Acceptable Use Policy',
        lastUpdated: 'February 15, 2026',
        icon: <UserCheck size={24} className="text-emerald-400" />,
        executiveSummary: 'This policy defines the standard behavior and intent required for maintaining an active TallyLink account. We prohibit the use of our infrastructure for any illegal or unethical activities.',
        articles: [
            {
                title: 'Article 1: Prohibited Financial Conduct',
                content: 'Users are strictly forbidden from utilizing TallyLink to facilitate or obfuscate illegal financial transactions.',
                subsections: [
                    { subtitle: '1.1 Tax Evasion', body: 'Misusing the platform to manipulate GSTR records or intentionally delete records to avoid statutory tax liability is grounds for immediate termination.' },
                    { subtitle: '1.2 Fraudulent Accounting', body: 'Synchronization of fictitious vouchers or shell-company ledgers is strictly prohibited.' }
                ]
            },
            {
                title: 'Article 2: Technical Integrity and Exploitation',
                content: 'We protect the stability of our platform through automated rate-limiting and behavior monitoring.',
                subsections: [
                    { subtitle: '2.1 API Scraping', body: 'Automated scraping or extraction of data from our dashboard without using official API endpoints is forbidden.' },
                    { subtitle: '2.2 Reverse Engineering', body: 'Attempts to decompile the Desktop Sync component or discover our proprietary sync algorithms will result in legal action.' }
                ]
            }
        ]
    },
    'data-processing-addendum': {
        title: 'Data Processing Addendum',
        lastUpdated: 'February 15, 2026',
        icon: <Database size={24} className="text-blue-500" />,
        executiveSummary: 'The DPA governs the processing of Personal Data and sensitive financial records. It strictly defines the roles and responsibilities of the Fiduciary and the Processor.',
        articles: [
            {
                title: 'Article 1: Processor Obligations',
                content: 'TallyLink, as a Data Processor, undertakes the following mandatory responsibilities:',
                subsections: [
                    { subtitle: '1.1 Purpose Limitation', body: 'Data is processed ONLY for provide the Tally cloud dashboard services requested by the Fiduciary.' },
                    { subtitle: '1.2 Notification of Breaches', body: 'We will notify the user within 72 hours of any confirmed security breach affecting their financial data.' }
                ]
            },
            {
                title: 'Article 2: Audit and Inspections',
                content: 'We provide transparency into our operational standards.',
                subsections: [
                    { subtitle: '2.1 Certification access', body: 'Users on Enterprise plans can request a summary of our annual internal security audits.' }
                ]
            }
        ]
    },
    'service-level-agreement': {
        title: 'Service Level Agreement',
        lastUpdated: 'February 15, 2026',
        icon: <Activity size={24} className="text-green-500" />,
        executiveSummary: 'Our SLA defines our commitment to platform reliability, data availability, and support response times.',
        articles: [
            {
                title: 'Article 1: Availability and Uptime Performance',
                content: 'We target an service availability of 99.9% for the Cloud Dashboard component.',
                subsections: [
                    { subtitle: '1.1 Downtime Definitions', body: 'Downtime excludes scheduled maintenance (usually Sunday 2-4 AM IST) and failures of the user’s local Tally computer/internet.' }
                ]
            },
            {
                title: 'Article 2: Sync Frequency Targets',
                content: 'Sync latency depends on the chosen plan tier.',
                subsections: [
                    { subtitle: '2.1 Batch Syncing', body: 'Free tiers sync once every 24 hours. Pro tiers sync every 15 minutes. Enterprise tiers sync in near real-time (<60 seconds).' }
                ]
            },
            {
                title: 'Article 3: Technical Support Response Time Targets (TAT)',
                content: 'We classify issues based on their impact on your business continuity.',
                subsections: [
                    { subtitle: '3.1 Sev-1 (Critical)', body: 'Platform completely down for all users. Target Response: 1 Hour. Target Resolution: 4 Hours.' },
                    { subtitle: '3.2 Sev-2 (Major)', body: 'Specific company sync failing. Target Response: 4 Hours. Target Resolution: 24 Hours.' },
                    { subtitle: '3.3 Sev-3 (Minor)', body: 'UI glitch or reporting discrepancy. Target Response: 24 Hours. Target Resolution: 72 Hours.' }
                ]
            },
            {
                title: 'Article 4: Data Consistency and Integrity Verification',
                content: 'Our commitment to the "Single Source of Truth" principle.',
                subsections: [
                    { subtitle: '4.1 Hashing Checks', body: 'We perform HMAC-based hashing on every sync packet to ensure data transmitted from Tally matches the data stored in the Cloud.' },
                    { subtitle: '4.2 Reconciliation Tools', body: 'We provide a "Sync Score" metric in the dashboard to let users identify if their cloud data is out-of-sync with local Tally totals.' }
                ]
            },
            {
                title: 'Article 5: Maintenance Windows and Service Noticing',
                content: 'Procedures for planned platform enhancements.',
                subsections: [
                    { subtitle: '5.1 Weekly Maintenance', body: 'Standard maintenance occurs every Sunday between 02:00 AM and 04:00 AM IST. Platforms may be intermittently unavailable.' },
                    { subtitle: '5.2 Emergency Patches', body: 'Critical security patches may be applied without notice if an active threat is detected. We aim for <15 mins downtime during such events.' }
                ]
            },
            {
                title: 'Article 6: Customer-Side Performance Dependencies',
                content: 'The SLA is a shared responsibility between TallyLink and the User.',
                subsections: [
                    { subtitle: '6.1 Local PC Resources', body: 'If the Tally PC has <4GB RAM or 100% CPU usage, sync latency targets are waived.' },
                    { subtitle: '6.2 ODBC Health', body: 'The user must ensure the Tally ODBC port (default 9000) is not blocked by local Windows Firewalls or Antivirus software.' }
                ]
            },
            {
                title: 'Article 7: Disaster Recovery (DR) and Continuity',
                content: 'Our strategy for catastrophic infrastructure failure.',
                subsections: [
                    { subtitle: '7.1 RPO (Recovery Point Objective)', body: 'We target a maximum data loss window of 15 minutes in case of a full regional cloud failure.' },
                    { subtitle: '7.2 RTO (Recovery Time Objective)', body: 'Target time to failover to a secondary cloud region: 4 Hours.' }
                ]
            },
            {
                title: 'Article 8: Breach of SLA and Service Credits',
                content: 'Legal remedy for failure to meet uptime commitments.',
                subsections: [
                    { subtitle: '8.1 Credit Calculation', body: 'If uptime falls below 95% in a month, users are entitled to a 10% credit of their monthly fee towards the next bill.' },
                    { subtitle: '8.2 Claims Procedure', body: 'Claims must be submitted within 7 days of the month-end via the SLA portal with supporting logs.' }
                ]
            },
            {
                title: 'Article 9: Exclusions and Limitations',
                content: 'Specific scenarios where the SLA does not apply.',
                subsections: [
                    { subtitle: '9.1 ISP Failures', body: 'Slow internet or DNS failures at the user’s office site are excluded from uptime calculations.' },
                    { subtitle: '9.2 Tally.exe Issues', body: 'If Tally.exe crashes or is closed by the user, TallyLink cannot extract data; such "downtime" is not counted against our SLA.' }
                ]
            },
            {
                title: 'Article 10: Performance Transparency and Monitoring',
                content: 'Trust through public metrics.',
                subsections: [
                    { subtitle: '10.1 Status Page', body: 'Real-time platform status is available at status.tallylink.cloud, showing uptime history for the last 90 days.' }
                ]
            }
        ]
    },
    'gst-compliance-statement': {
        title: 'GST Compliance',
        lastUpdated: 'February 15, 2026',
        icon: <Scale size={24} className="text-amber-500" />,
        executiveSummary: 'TallyLink is built for the Indian tax ecosystem. We ensure our data extraction and report generation follow statutory GST rules defined by the CBIC.',
        articles: [
            {
                title: 'Article 1: Statutory Reporting and Validity',
                content: 'Reports generated on TallyLink (GSTR-1, GSTR-3B) are intended as advisory summaries for reconciliation.',
                subsections: [
                    { subtitle: '1.1 Verification Required', body: 'Users must verify TallyLink summaries with their Chartered Accountant before official filing on the GSTN portal.' }
                ]
            },
            {
                title: 'Article 2: E-Invoicing and QR Compliance',
                content: 'We support the extraction of E-Invoice IRNs and Ack IDs from Tally.',
                subsections: [
                    { subtitle: '2.1 IRN Mapping', body: 'We store and display IRN numbers and E-Way Bill details extracted from Tally to assist in road-transit audits.' }
                ]
            },
            {
                title: 'Article 3: HSN/SAC Code Semantic Mapping',
                content: 'Our system identifies and categorizes goods and services as per the latest GST Tariff.',
                subsections: [
                    { subtitle: '3.1 HSN Validation', body: 'The dashboard highlights stock items with missing or invalid HSN codes (less than 4/6/8 digits based on turnover) to ensure your invoices pass portal validation.' }
                ]
            },
            {
                title: 'Article 4: GSTR-2A and 2B Reconciliation Engine',
                content: 'Helping users maximize Input Tax Credit (ITC) with data-driven insights.',
                subsections: [
                    { subtitle: '4.1 Auto-Matching', body: 'Our engine compares "Purchase Vouchers" in Tally with "GSTR-2B" data (if uploaded) to flag missing invoices or mismatched amounts.' },
                    { subtitle: '4.2 Vendor Communication', body: 'Integrated WhatsApp alerts allow you to notify vendors directly from the dashboard if they have not uploaded their B2B invoices.' }
                ]
            },
            {
                title: 'Article 5: E-Way Bill Lifecycle and Transit Logs',
                content: 'Detailed tracking of inter-state movement documentation.',
                subsections: [
                    { subtitle: '5.1 EWB Validity', body: 'The dashboard displays E-Way Bill validity dates and alerts you if a vehicle is in transit without a valid extension.' }
                ]
            },
            {
                title: 'Article 6: Reverse Charge Mechanism (RCM) Detection',
                content: 'Automated identification of tax liability on inward supplies.',
                subsections: [
                    { subtitle: '6.1 RCM Flags', body: 'Transactions categorized under RCM in Tally are specifically tagged in the dashboard to ensure the correct tax liability is shown in the GSTR-3B summary.' }
                ]
            },
            {
                title: 'Article 7: TDS and TCS Extraction Framework',
                content: 'Handling complementary taxes integrated within the GST ecosystem.',
                subsections: [
                    { subtitle: '7.1 Section Mapping', body: 'We extract TDS (Income Tax) and TCS (Sale of Goods) fields to provide a unified compliance view alongside GST.' }
                ]
            },
            {
                title: 'Article 8: Multi-State GSTIN and Consolidation',
                content: 'Provisions for PAN-India enterprises.',
                subsections: [
                    { subtitle: '8.1 State-wise Reporting', body: 'For users with multiple branches, we provide state-wise GST summaries (based on Place of Supply) to aid in filing for different registrations.' }
                ]
            },
            {
                title: 'Article 9: Audit Trail and Log Maintenance for Officers',
                content: 'Preparing you for potential GST Department scrutiny.',
                subsections: [
                    { subtitle: '9.1 Edit Logs', body: 'We maintain a log of when data was synced and any subsequent manual adjustments made in the dashboard to ensure a clean audit trail for tax officers.' }
                ]
            },
            {
                title: 'Article 10: Liability Limitation on External Filings',
                content: 'Defining the boundary of our responsibility.',
                subsections: [
                    { subtitle: '10.1 No Auto-Filing', body: 'TallyLink DOES NOT push data directly to the GSTN Portal. All filings must be performed by the User or their authorized CA after verifying the TallyLink advisory reports.' }
                ]
            }
        ]
    },
    'billing-and-subscription': {
        title: 'Billing Policy',
        lastUpdated: 'February 15, 2026',
        icon: <CreditCard size={24} className="text-indigo-500" />,
        executiveSummary: 'This document defines the commercials, tax handling, and billing cycles for TallyLink services.',
        articles: [
            {
                title: 'Article 1: Subscription Cycles',
                content: 'We offer standardized billing cycles designed for business budgeting.',
                subsections: [
                    { subtitle: '1.1 Monthly Recurring', body: 'Billed on the same date every month. Failure to pay within 5 days results in sync suspension.' },
                    { subtitle: '1.2 Annual Commitment', body: 'Annual plans are paid upfront and are non-terminable for 12 months in exchange for higher discounts.' }
                ]
            },
            {
                title: 'Article 2: Multi-Company and Pro-Rata Scaling',
                content: 'Handling licenses for groups with multiple Tally companies.',
                subsections: [
                    { subtitle: '2.1 Incremental Addition', body: 'New companies added mid-month are charged a pro-rata amount for the remaining days in that cycle.' },
                    { subtitle: '2.2 License Splitting', body: 'A single Tally Serial Number may contain multiple companies; each company activated on the cloud dashboard consumes one license slot.' }
                ]
            },
            {
                title: 'Article 3: Payment Delinquency and Recovery',
                content: 'Protocols for handling failed transactions.',
                subsections: [
                    { subtitle: '3.1 Grace Period', body: 'We offer a 48-hour grace period for technical gateway failures. After 48 hours, "Live Sync" is disabled while "ReadOnly View" remains active for 3 days.' },
                    { subtitle: '3.2 Restoration Fee', body: 'Accounts inactive for >30 days due to non-payment may incur a ₹500 restoration fee to cover cold-storage retrieval costs.' }
                ]
            },
            {
                title: 'Article 4: Tax Invoicing and GST Compliance',
                content: 'Ensuring your subscription cost is GST-recoverable.',
                subsections: [
                    { subtitle: '4.1 Digitally Signed Invoices', body: 'All invoices are digitally signed and contain our GSTIN. You can download these for input tax credit (ITC) claims from the "Billing History" tab.' }
                ]
            }
        ]
    },
    'intellectual-property-policy': {
        title: 'Intellectual Property',
        lastUpdated: 'February 15, 2026',
        icon: <Globe size={24} className="text-sky-500" />,
        executiveSummary: 'This policy governs the ownership of software, branding, and user-generated data metadata.',
        articles: [
            {
                title: 'Article 1: TallyLink Proprietary Rights',
                content: 'All source code, UI designs, and sync algorithms are the exclusive intellectual property of TallyLink Technologies.',
                subsections: [
                    { subtitle: '1.1 Trade Secrets', body: 'The mechanism of Tally-to-Cloud parsing is a protected trade secret. Any unauthorized reproduction is a violation of law.' }
                ]
            },
            {
                title: 'Article 2: User Data Ownership vs Metadata',
                content: 'Defining who owns what in the cloud ecosystem.',
                subsections: [
                    { subtitle: '2.1 Absolute Ownership', body: 'The User retains 100% legal ownership of the accounting records (Vouchers/Ledgers) synchronized to our servers.' },
                    { subtitle: '2.2 System Metadata', body: 'TallyLink owns the "System Metadata" (aggregated, anonymized performance stats) used to improve platform stability.' }
                ]
            },
            {
                title: 'Article 3: Trademark Usage and Branding Guidelines',
                content: 'Rules for partners and CAs referencing our brand.',
                subsections: [
                    { subtitle: '3.1 Permitted Use', body: 'Verified partners may use the "TallyLink Powered" badge on their websites, provided it links directly to our official portal.' }
                ]
            }
        ]
    },
    'disclaimer-and-liability': {
        title: 'Disclaimer & Liability',
        lastUpdated: 'February 15, 2026',
        icon: <AlertTriangle size={24} className="text-red-500" />,
        executiveSummary: 'This disclaimer outlines the limits of our responsibility regarding the financial accuracy of synchronized reports.',
        articles: [
            {
                title: 'Article 1: No Financial Advice',
                content: 'TallyLink is a data visualization tool. It does not provide accounting, tax, or legal advice.',
                subsections: [
                    { subtitle: '1.1 Final Responsibility', body: 'The accuracy of the Balance Sheet and P&L results from the original Tally entries. TallyLink is not responsible for penalties due to fundamental book-keeping errors.' }
                ]
            },
            {
                title: 'Article 2: Hardware and Environmental Disclaimer',
                content: 'We are not liable for failures originating outside our cloud perimeter.',
                subsections: [
                    { subtitle: '2.1 Local Hardware Failure', body: 'We are not responsible for data loss arising from hard drive crashes, power surges, or ransomware attacks on the User’s local Tally computer.' }
                ]
            },
            {
                title: 'Article 3: ISP and Internet Backbone Outages',
                content: 'Acknowledging the limitations of global networking.',
                subsections: [
                    { subtitle: '3.1 Transit Liability', body: 'We are not liable for delays caused by national ISP outages, Tier-1 carrier failures, or sub-marine cable cuts that affect data transit between Jaipur and our cloud regions.' }
                ]
            },
            {
                title: 'Article 4: External Data Accuracy (GIGO)',
                content: 'The "Garbage In, Garbage Out" principle.',
                subsections: [
                    { subtitle: '4.1 Original Entry', body: 'If a transaction is entered incorrectly in Tally, TallyLink will display it incorrectly. We do not perform forensic audits of your original accounting entries.' }
                ]
            }
        ]
    },
    'indemnification-policy': {
        title: 'Indemnification Policy',
        lastUpdated: 'February 15, 2026',
        icon: <Shield size={24} className="text-orange-500" />,
        executiveSummary: 'This policy defines how legal costs and damages will be handled in the event of a dispute.',
        articles: [
            {
                title: 'Article 1: Mutual Indemnity',
                content: 'Both parties agree to protect each other against specific defined legal claims.',
                subsections: [
                    { subtitle: '1.1 User Indemnity', body: 'User agrees to indemnify TallyLink against claims from tax authorities if fraudulent synchronization led to tax notices.' }
                ]
            },
            {
                title: 'Article 2: Intellectual Property Indemnity',
                content: 'We protect our users against claims of third-party IP infringement.',
                subsections: [
                    { subtitle: '2.1 Non-Infringement', body: 'If TallyLink software is found to infringe on a third-party patent, we will indemnify the user against legal judgments, provided the user was using the latest official version.' }
                ]
            }
        ]
    },
    'termination-policy': {
        title: 'Termination Policy',
        lastUpdated: 'February 15, 2026',
        icon: <LogOut size={24} className="text-gray-500" />,
        executiveSummary: 'This document specifies how an account relationship is ended and how data is handled post-termination.',
        articles: [
            {
                title: 'Article 1: Voluntary Termination',
                content: 'Users can delete their account at any time through the security settings.',
                subsections: [
                    { subtitle: '1.1 Data Purge', body: 'Upon voluntary deletion, all database records for that user are queued for permanent deletion within 24 hours.' }
                ]
            },
            {
                title: 'Article 2: Termination for Cause',
                content: 'Immediate cessation of service for specific breaches.',
                subsections: [
                    { subtitle: '2.1 Prohibited Use', body: 'We may terminate account access without notice if the user is found using the software for money laundering or unauthorized scraping.' }
                ]
            }
        ]
    },
    'user-grievance-redressal': {
        title: 'Grievance Redressal',
        lastUpdated: 'February 15, 2026',
        icon: <Info size={24} className="text-blue-600" />,
        executiveSummary: 'In compliance with Indian IT laws, we provide a formal channel for grievance redressal.',
        articles: [
            {
                title: 'Article 1: Reporting Mechanism',
                content: 'Grievances regarding data misuse, harassment, or security flaws should be reported via the official channel.',
                subsections: [
                    { subtitle: '1.1 Grievance Officer', body: `Officer Name: ${CONFIG.dpoName}. Contact: ${CONFIG.supportEmail}. Response TAT: 48 Hours.` }
                ]
            },
            {
                title: 'Article 2: Escalation Path',
                content: 'If a grievance is not resolved within the defined TAT, users can escalate to senior management.',
                subsections: [
                    { subtitle: '2.1 Senior Review', body: 'Unresolved issues may be escalated to management@tallylink.cloud for secondary review and final arbitration.' }
                ]
            }
        ]
    },
    'sub-processor-list': {
        title: 'Sub-processors',
        lastUpdated: 'February 15, 2026',
        icon: <Database size={24} className="text-green-600" />,
        executiveSummary: 'A transparent list of third-party vendors who handle parts of your data infrastructure.',
        articles: [
            {
                title: 'Article 1: Cloud Providers',
                content: 'We use globally recognized infrastructure partners.',
                subsections: [
                    { subtitle: '1.1 Storage & DB', body: 'Supabase Inc. (Database and Auth), Vercel (Edge Functions and Hosting).' },
                    { subtitle: '1.2 Backup storage', body: 'Amazon Web Services (AWS) S3 in the India (Mumbai) region for off-site backups.' }
                ]
            },
            {
                title: 'Article 2: Communication and Payments',
                content: 'Vendors handling transactional workflows.',
                subsections: [
                    { subtitle: '2.1 Payment Gateway', body: 'Razorpay Software Pvt Ltd handles all INR transactions and card data tokenization.' },
                    { subtitle: '2.2 WhatsApp Alerts', body: 'Twilio Inc. / Meta Platforms for delivering ledger reports and OTPs.' }
                ]
            }
        ]
    },
    'anti-spam-policy': {
        title: 'Anti-Spam Policy',
        lastUpdated: 'February 15, 2026',
        icon: <Mail size={24} className="text-yellow-600" />,
        executiveSummary: 'Ensuring our communication tools (WhatsApp/Email) are used ONLY for legitimate business reporting.',
        articles: [
            {
                title: 'Article 1: WhatsApp Bulk Messaging',
                content: 'The WhatsApp integration is intended for sending ledger reports to active customers only.',
                subsections: [
                    { subtitle: '1.1 Prohibited Use', body: 'Sending bulk promotional "marketing" blasts to non-customers will lead to immediate WhatsApp API revocation.' }
                ]
            },
            {
                title: 'Article 2: Opt-Out and Consent',
                content: 'Respecting the recipient’s right to stop communication.',
                subsections: [
                    { subtitle: '2.1 Unsubscribe Link', body: 'All TallyLink automated emails and WhatsApp footers must include a clear opt-out command or link.' }
                ]
            }
        ]
    },
    'third-party-disclosures': {
        title: 'Third Party Disclosures',
        lastUpdated: 'February 15, 2026',
        icon: <Share2 size={24} className="text-cyan-600" />,
        executiveSummary: 'Clarifying our relationship with third-party software vendors including Tally Solutions.',
        articles: [
            {
                title: 'Article 1: Tally Solutions Relationship',
                content: 'TallyLink is an independent developer. We are not officially affiliated with Tally Solutions Pvt. Ltd.',
                subsections: [
                    { subtitle: '1.1 No Endorsement', body: 'Tally Solutions does not endorse or warranty TallyLink. Use is at the customer’s discretion.' }
                ]
            },
            {
                title: 'Article 2: API and OEM Limitations',
                content: 'We respect the IP limits of original equipment manufacturers.',
                subsections: [
                    { subtitle: '2.1 Respect for Licences', body: 'TallyLink requires the user to have a valid, licensed copy of Tally ERP 9 or TallyPrime to function correctly.' }
                ]
            }
        ]
    },
    'compliance-with-indian-laws': {
        title: 'Compliance Statement',
        lastUpdated: 'February 15, 2026',
        icon: <Building2 size={24} className="text-gray-800" />,
        executiveSummary: 'A summary of the legal framework under which TallySync Technologies operates in India.',
        articles: [
            {
                title: 'Article 1: Information Technology Act',
                content: 'We comply with Section 43A of the IT Act regarding reasonable security practices for protecting personal data.',
                subsections: [
                    { subtitle: '1.1 Data Residency', body: 'To comply with financial regulations, primary cloud storage for Indian companies is provisioned in the India-South/India-West cloud regions.' }
                ]
            },
            {
                title: 'Article 2: Companies Act and Audit Requirements',
                content: 'How our records assist in statutory compliance.',
                subsections: [
                    { subtitle: '2.1 Books of Account', body: 'TallyLink maintains records that assist companies in fulfilling their duties under Section 128 of the Companies Act, 2013 regarding electronic maintenance of accounts.' }
                ]
            }
        ]
    },
    'accessibility-statement': {
        title: 'Accessibility',
        lastUpdated: 'February 15, 2026',
        icon: <Search size={24} className="text-blue-400" />,
        executiveSummary: 'Commitment to providing an inclusive dashboard experience for all users.',
        articles: [
            {
                title: 'Article 1: WCAG 2.1 Compliance',
                content: 'We aim to follow Web Content Accessibility Guidelines to ensure reports are readable by screen-readers.',
                subsections: [
                    { subtitle: '1.1 High Contrast Mode', body: 'Our Dark Theme is designed with high contrast ratios for low-vision users.' }
                ]
            },
            {
                title: 'Article 2: Inclusivity in Design',
                content: 'Ensuring the dashboard works for users with varying physical capabilities.',
                subsections: [
                    { subtitle: '2.1 Keyboard Navigation', body: 'Major dashboard features are accessible via keyboard shortcuts (Tab/Enter) without requiring a mouse.' }
                ]
            }
        ]
    }
};
